apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "svc-meta-saga-v2.fullname" . }}
  labels:
    {{- include "svc-meta-saga-v2.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "svc-meta-saga-v2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        - {{- toYaml . | nindent 8 }}
          rollme: {{ randAlphaNum 5 | quote }}
    {{- end }}
      labels:
        {{- include "svc-meta-saga-v2.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "svc-meta-saga-v2.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: health-port
              containerPort: 3000
            - name: saga-v2
              containerPort: 9000 
              protocol: TCP
          env:
            - name: MIX_ENV
              value: prod
          livenessProbe:
            httpGet:
              path: /liveness
              port: health-port
            failureThreshold: 1
            periodSeconds: 10 
          readinessProbe:
            httpGet:
              path: /readiness
              port: health-port
            failureThreshold: 1
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
