apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  AEON_ETCD_CLUSTER: {{ .Values.AEON_ETCD_CLUSTER | b64enc }}
  AEON_ETCD_USER: {{ .Values.AEON_ETCD_USER | b64enc }}
  AEON_ETCD_PASSWORD: {{ .Values.AEON_ETCD_PASSWORD | b64enc }}
