version: '2.1'
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380

  service:
    build:
      context: ../../.
      dockerfile: ./ops/docker/server.Dockerfile
      args:
        - 'SSH_PRIVATE_KEY=${GITLAB_SSH_PRIVATE_KEY}'
        - 'SSH_PUBLIC_KEY=${GITLAB_SSH_PUBLIC_KEY}'

